version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: development
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/postgres
    depends_on: [db]
    volumes:
      - .:/usr/src/app
    ports:
      - 8080:8080
  db:
    image: postgres:14.2
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432

volumes:
  postgres-data: null